name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Verify
    uses: maveniverse/parent/.github/workflows/ci.yml@release-39
    with:
      jdk-matrix: '[ "8", "17", "21", "24" ]'
      maven-matrix: '[ "3.9.9" ]'
      maven-test: './mvnw clean verify -e -B -V -P run-its'